# Generated by Django for the water_quality app.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Water temperature')),
                ('ph', models.FloatField(verbose_name='pH')),
                ('dissolved_oxygen', models.FloatField(verbose_name='Dissolved oxygen')),
                ('ammonia', models.FloatField(verbose_name='Ammonia')),
                ('nitrite', models.FloatField(verbose_name='Nitrite')),
                ('nitrate', models.FloatField(verbose_name='Nitrate')),
                ('turbidity', models.FloatField(verbose_name='Turbidity')),
                ('salinity', models.FloatField(blank=True, null=True, verbose_name='Salinity')),
                ('water_level', models.FloatField(verbose_name='Water level')),
                ('overall_status', models.CharField(choices=[('Good', 'Good'), ('Warning', 'Warning'), ('Danger', 'Danger')], default='Good', max_length=16, verbose_name='Overall status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_quality_readings', to='store.pond', verbose_name='Pond')),
            ],
            options={
                'verbose_name': 'Water quality reading',
                'verbose_name_plural': 'Water quality readings',
                'ordering': ['-created_at'],
            },
        ),
    ]
