# Generated by Codex for the weather app.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_query', models.CharField(max_length=180)),
                ('resolved_location', models.CharField(max_length=220)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timezone', models.CharField(blank=True, max_length=80)),
                ('observed_at', models.DateTimeField()),
                ('forecast_date', models.DateField()),
                ('air_temperature', models.FloatField()),
                ('rainfall_probability', models.FloatField()),
                ('rainfall_mm', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('humidity', models.FloatField()),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('cloud_cover', models.FloatField()),
                ('atmospheric_pressure', models.FloatField()),
                ('weather_code', models.IntegerField(blank=True, null=True)),
                ('fish_weather_risk', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Low', max_length=16)),
                ('disease_risk', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Low', max_length=16)),
                ('pond_impact', models.JSONField(default=dict)),
                ('feeding_recommendation', models.JSONField(default=list)),
                ('do_prediction', models.JSONField(default=dict)),
                ('rain_impact', models.JSONField(default=dict)),
                ('alerts', models.JSONField(default=list)),
                ('forecast', models.JSONField(default=list)),
                ('raw_payload', models.JSONField(default=dict)),
                ('source', models.CharField(default='OpenWeather', max_length=80)),
                ('source_url', models.URLField(default='https://openweathermap.org/api')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_reports', to='store.pond')),
            ],
            options={
                'ordering': ['-observed_at', '-created_at'],
                'indexes': [models.Index(fields=['pond', '-observed_at'], name='weather_wea_pond_id_8f962b_idx')],
            },
        ),
    ]
