# Generated by Django 6.0.6 on 2026-07-16 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=180)),
                ('area_decimal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('average_depth_ft', models.DecimalField(decimal_places=2, max_digits=5)),
                ('water_source', models.CharField(choices=[('rainwater', 'Rainwater'), ('river', 'River'), ('deep_tubewell', 'Deep tubewell'), ('canal', 'Canal'), ('mixed', 'Mixed')], default='mixed', max_length=24)),
                ('stocking_capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_pond_name_per_owner'), models.CheckConstraint(condition=models.Q(('area_decimal__gt', 0)), name='pond_area_decimal_positive'), models.CheckConstraint(condition=models.Q(('average_depth_ft__gt', 0)), name='pond_average_depth_positive'), models.CheckConstraint(condition=models.Q(('stocking_capacity__gt', 0)), name='pond_stocking_capacity_positive')],
            },
        ),
    ]
