# Generated by Django 6.0.6 on 2026-07-17 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=120)),
                ('batch_name', models.CharField(max_length=120)),
                ('stocking_date', models.DateField()),
                ('initial_quantity', models.PositiveIntegerField()),
                ('current_quantity', models.PositiveIntegerField()),
                ('initial_average_weight_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('partial_harvest', 'Partial harvest'), ('harvested', 'Harvested')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='store.pond')),
            ],
            options={
                'ordering': ['pond__name', '-stocking_date', 'species'],
            },
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField()),
                ('sample_count', models.PositiveIntegerField()),
                ('average_weight_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('average_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mortality_count', models.PositiveIntegerField(default=0)),
                ('feed_used_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='store.fishstock')),
            ],
            options={
                'ordering': ['stock__pond__name', 'stock__batch_name', 'recorded_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='fishstock',
            constraint=models.UniqueConstraint(fields=('pond', 'batch_name'), name='unique_stock_batch_name_per_pond'),
        ),
        migrations.AddConstraint(
            model_name='fishstock',
            constraint=models.CheckConstraint(condition=models.Q(('initial_quantity__gt', 0)), name='stock_initial_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='fishstock',
            constraint=models.CheckConstraint(condition=models.Q(('current_quantity__gte', 0)), name='stock_current_quantity_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='fishstock',
            constraint=models.CheckConstraint(condition=models.Q(('initial_average_weight_g__gt', 0)), name='stock_initial_average_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='growthrecord',
            constraint=models.UniqueConstraint(fields=('stock', 'recorded_date'), name='unique_growth_record_date_per_stock'),
        ),
        migrations.AddConstraint(
            model_name='growthrecord',
            constraint=models.CheckConstraint(condition=models.Q(('sample_count__gt', 0)), name='growth_sample_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='growthrecord',
            constraint=models.CheckConstraint(condition=models.Q(('average_weight_g__gt', 0)), name='growth_average_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='growthrecord',
            constraint=models.CheckConstraint(condition=models.Q(('average_length_cm__isnull', True), ('average_length_cm__gt', 0), _connector='OR'), name='growth_average_length_positive_when_set'),
        ),
        migrations.AddConstraint(
            model_name='growthrecord',
            constraint=models.CheckConstraint(condition=models.Q(('mortality_count__gte', 0)), name='growth_mortality_count_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='growthrecord',
            constraint=models.CheckConstraint(condition=models.Q(('feed_used_kg__isnull', True), ('feed_used_kg__gt', 0), _connector='OR'), name='growth_feed_used_positive_when_set'),
        ),
    ]
